### ISSUE TITLE
Incorrect return type in readFileSync() when the encoding option is provided

### ISSUE THREAD

**Issue by alisey** [wixplosives/file-services#258] opened 2020-12-18 09:01 UTC
```ts
import fs from 'fs';
import { createNodeFs } from '@file-services/node';

const FS = createNodeFs();

// Return type mismatch
fs.readFileSync('foo', {encoding: 'gibberish'}); // string (throws)
FS.readFileSync('foo', {encoding: 'gibberish'}); // string | Buffer

// Also changes depending on whether there's a dash
FS.readFileSync('foo', {encoding: 'utf8'}); // string
FS.readFileSync('foo', {encoding: 'utf-8'}); // string | Buffer
```

As a result, I see this pattern in our project:
```ts
return fs.readFileSync(filePath, 'utf-8') as string;
```

The native fs module treats `utf8` and `utf-8` identically, as well as `UTF-8` and `UTF8`.

**Comment by AviVahl** [comment] 2020-12-18 12:55
@types/node@10 define `BufferEncoding` as:
`type BufferEncoding = "ascii" | "utf8" | "utf16le" | "ucs2" | "base64" | "latin1" | "binary" | "hex";`

@types/node@12 defines `BufferEncoding` as:
`type BufferEncoding = "ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex";`

Since `@file-services` has minimum support of node 10, I've used `@types/node@10` here. `@file-services/types` are just a subset of that, including its overload behavior.

That's the root cause. The `fs` types differ slightly depending on which `@types/node` version you depend on.

How to resolve? I could use @types/node@12 here to get the updated types (without dropping node 10 support by testing it in CI). That's probably the most graceful way forward.

Should be noted there's a good chance there are further differences between `@types/node@12` and `@types/node@14` in regards with the fs types. We'll find out once our projects start dropping Node 12 and moving to 14 as default.

**Comment by AviVahl** [comment] 2020-12-18 13:00
Just checked... in `@types/node@14`, `fs.readFileSync('/some-path', 'gibberish')` is a **type error**...
I may end up picking the behavior of `@types/node@14`.

**Closed** 2020-12-20 17:01 UTC
